export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_ERRORS = 'SET_ERRORS';

export const AUTOFILL_TERM = 'AUTOFILL_TERM';
export const UPDATE_FIELD_TERM = 'UPDATE_FIELD_TERM';

export const SELECT_APARTMENT = 'SELECT_APARTMENT';

export const FETCH_APARTMENT_SUCCESS = 'FETCH_APARTMENT_SUCCESS';
export const FETCH_APARTMENT_REQUEST = 'FETCH_APARTMENT_REQUEST';
export const FETCH_APARTMENT_FAILURE = 'FETCH_APARTMENT_FAILURE';
